#+ summary: Get methods for all Key Events of an Adverse Outcome Pathway. For the variable of aopfilter, fill the identifier of the AOP (only the number)
#+ endpoint_in_url: False
#+ tags:
#+   - Methods
#+ defaults:
#+   - aopfilter: 3

prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix aop: <http://identifiers.org/aop/>
prefix aopo: <http://aopkb.org/aop_ontology#>
prefix mmo: <http://purl.obolibrary.org/obo/MMO_>

select   (?_aopfilter_integer AS ?AOPfilter) ?AopLabel ?KeLookUp ?AssayText 
where {
 ?KeLook a aopo:KeyEvent ;
 rdfs:label ?KeLookUp ;
 dcterms:isPartOf  ?aop; 
 mmo:0000000 ?AssayText .
 ?aop rdfs:label ?AopLabel .
BIND(IRI(CONCAT("http://identifiers.org/aop/",?_aopfilter_integer)) AS ?AOPp )
FILTER (?aop = ?AOPp)
}
