#+ summary: Get Stressor Chemicals described to initiate AOPs that lead to selected Adverse Outcome (ID).
#+ endpoint_in_url: False
#+ tags:
#+   - Chemicals
#+   - Adverse Outcome
#+ defaults:
#+   - aofilter: 344

prefix dc:  <http://purl.org/dc/elements/1.1/> 
prefix aop: <http://identifiers.org/aop/> 
prefix aopo: <http://aopkb.org/aop_ontology#> 
prefix ke: <http://identifiers.org/aop.events/>
PREFIX nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

SELECT ?AO ?AOname ?StressorName ?ChemicalName WHERE { 
  ?AO a aopo:KeyEvent ; 
  dc:identifier ?AOLookup ; 
  dc:title ?AOname . 
  ?AOP a aopo:AdverseOutcomePathway ; 
  aopo:has_adverse_outcome ?AOLookup ;
  nci:C54571 ?Stressor .
  ?Stressor dc:title ?StressorName.
  OPTIONAL {?Stressor aopo:has_chemical_entity ?Chemical. ?Chemical dc:title ?ChemicalName.}
  BIND(IRI(CONCAT("http://identifiers.org/aop.events/",?_aofilter_integer)) AS ?AOf )
  FILTER (?AO = ?AOf)}
  ORDER BY DESC (?AO)
