#+ summary: Get all chemical that are part of a particular AOP.
#+ endpoint_in_url: False
#+ tags:
#+   - Adverse Outcome Pathways
#+   - Chemicals
#+ defaults:
#+   - aopfilter: http://identifiers.org/aop/37

PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
SELECT ?CAS_ID (fn:substring(?CompTox,33) as ?CompTox_ID)
WHERE{
?_aopfilter_iri a aopo:AdverseOutcomePathway; ncit:C54571 ?Stressor.
?Stressor aopo:has_chemical_entity ?Chemical.
?Chemical cheminf:CHEMINF_000446 ?CAS_ID.
OPTIONAL {?Chemical cheminf:CHEMINF_000568 ?CompTox.}}
