#+ summary: Get AOP for a specific chemical (ChEBI ID). Use the ChEBI ID without "ChEBI" in front for the filter.
#+ endpoint_in_url: False
#+ tags:
#+   - Adverse Outcome Pathways
#+ defaults:
#+   - ChEBIfilter: 16605


PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX cheminf: <http://semanticscience.org/resource/CHEMINF_>

SELECT ?ChEBI ?ChemicalName ?AOPwebpage ?AdverseOutcomePathwayName
WHERE {
 ?matchID cheminf:000407 ?ChEBI .
 ?CAS skos:exactMatch ?matchID ;
 dc:title ?ChemicalName ;
 dcterms:isPartOf ?Stressor .
 ?Stressor  a nci:C54571 ;
 dcterms:isPartOf ?AOPwebpage .
 ?AOPwebpage a aopo:AdverseOutcomePathway ;
 dc:title ?AdverseOutcomePathwayName .
FILTER regex (?ChEBI, ?_ChEBIfilter_en, "i")
}
