#+ summary: Lookup all MIEs that lead to a certain AO.
#+ endpoint: http://aopwiki-rdf.prod.openrisknet.org/sparql/
#+ method: GET

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX aop: <http://identifiers.org/aop/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>

SELECT ?KE ?KEname ?AOP ?AOPname ?MIE ?MIEname WHERE {
 ?KE a aopo:KeyEvent ;
 dc:identifier ?AOLookup ;
 dc:title ?KEname .
 ?AOP a aopo:AdverseOutcomePathway ;
 dc:title ?AOPname ;
 aopo:has_adverse_outcome ?AOLookup;
 aopo:has_molecular_initiating_event ?MIE.
 ?MIE dc:title ?MIEname .
 FILTER (?KE = ke:345) 
}
