#+ summary: Get methods for all Key Events of an Adverse Outcome Pathway.
#+ endpoint: http://aopwiki-rdf.prod.openrisknet.org/sparql/
#+ endpoint_in_url: False
#+ enumerate:
#+   - aopfilter:
#+     - http://identifiers.org/aop/1
#+     - http://identifiers.org/aop/3
#+     - http://identifiers.org/aop/4
#+     - http://identifiers.org/aop/5
#+     - http://identifiers.org/aop/6
#+     - http://identifiers.org/aop/7
#+     - http://identifiers.org/aop/8
#+     - http://identifiers.org/aop/10
#+     - http://identifiers.org/aop/11
#+     - http://identifiers.org/aop/12
#+     - http://identifiers.org/aop/13
#+     - http://identifiers.org/aop/14
#+     - http://identifiers.org/aop/15
#+     - http://identifiers.org/aop/16
#+     - http://identifiers.org/aop/17
#+     - http://identifiers.org/aop/18
#+     - http://identifiers.org/aop/19
#+     - http://identifiers.org/aop/21
#+     - http://identifiers.org/aop/23
#+     - http://identifiers.org/aop/25
#+     - http://identifiers.org/aop/26
#+     - http://identifiers.org/aop/27
#+     - http://identifiers.org/aop/28
#+     - http://identifiers.org/aop/29
#+     - http://identifiers.org/aop/30
#+     - http://identifiers.org/aop/31
#+     - http://identifiers.org/aop/32
#+     - http://identifiers.org/aop/33
#+     - http://identifiers.org/aop/34
#+     - http://identifiers.org/aop/35
#+     - http://identifiers.org/aop/36
#+     - http://identifiers.org/aop/37
#+     - http://identifiers.org/aop/38
#+     - http://identifiers.org/aop/39
#+     - http://identifiers.org/aop/40
#+     - http://identifiers.org/aop/41
#+     - http://identifiers.org/aop/42
#+     - http://identifiers.org/aop/43
#+     - http://identifiers.org/aop/44
#+     - http://identifiers.org/aop/45
#+     - http://identifiers.org/aop/46
#+     - http://identifiers.org/aop/48
#+     - http://identifiers.org/aop/51
#+     - http://identifiers.org/aop/52
#+     - http://identifiers.org/aop/53
#+     - http://identifiers.org/aop/54
#+     - http://identifiers.org/aop/57
#+     - http://identifiers.org/aop/58
#+     - http://identifiers.org/aop/59
#+     - http://identifiers.org/aop/60
#+     - http://identifiers.org/aop/61
#+     - http://identifiers.org/aop/62
#+     - http://identifiers.org/aop/63
#+     - http://identifiers.org/aop/64
#+     - http://identifiers.org/aop/65
#+     - http://identifiers.org/aop/66
#+     - http://identifiers.org/aop/67
#+     - http://identifiers.org/aop/68
#+     - http://identifiers.org/aop/69
#+     - http://identifiers.org/aop/70
#+     - http://identifiers.org/aop/71
#+     - http://identifiers.org/aop/72
#+     - http://identifiers.org/aop/73
#+     - http://identifiers.org/aop/74
#+     - http://identifiers.org/aop/77
#+     - http://identifiers.org/aop/78
#+     - http://identifiers.org/aop/79
#+     - http://identifiers.org/aop/80
#+     - http://identifiers.org/aop/81
#+     - http://identifiers.org/aop/82
#+     - http://identifiers.org/aop/84
#+     - http://identifiers.org/aop/85
#+     - http://identifiers.org/aop/86
#+     - http://identifiers.org/aop/87
#+     - http://identifiers.org/aop/88
#+     - http://identifiers.org/aop/89
#+     - http://identifiers.org/aop/90
#+     - http://identifiers.org/aop/91
#+     - http://identifiers.org/aop/93
#+     - http://identifiers.org/aop/94
#+     - http://identifiers.org/aop/95
#+     - http://identifiers.org/aop/96
#+     - http://identifiers.org/aop/97
#+     - http://identifiers.org/aop/98
#+     - http://identifiers.org/aop/99
#+     - http://identifiers.org/aop/100
#+     - http://identifiers.org/aop/101
#+     - http://identifiers.org/aop/102
#+     - http://identifiers.org/aop/103
#+     - http://identifiers.org/aop/104
#+     - http://identifiers.org/aop/105
#+     - http://identifiers.org/aop/106
#+     - http://identifiers.org/aop/107
#+     - http://identifiers.org/aop/108
#+     - http://identifiers.org/aop/109
#+     - http://identifiers.org/aop/110
#+     - http://identifiers.org/aop/111
#+     - http://identifiers.org/aop/112
#+     - http://identifiers.org/aop/113
#+     - http://identifiers.org/aop/114
#+     - http://identifiers.org/aop/115
#+     - http://identifiers.org/aop/116
#+     - http://identifiers.org/aop/117
#+     - http://identifiers.org/aop/118
#+     - http://identifiers.org/aop/119
#+     - http://identifiers.org/aop/120
#+     - http://identifiers.org/aop/121
#+     - http://identifiers.org/aop/122
#+     - http://identifiers.org/aop/123
#+     - http://identifiers.org/aop/124
#+     - http://identifiers.org/aop/126
#+     - http://identifiers.org/aop/128
#+     - http://identifiers.org/aop/130
#+     - http://identifiers.org/aop/131
#+     - http://identifiers.org/aop/134
#+     - http://identifiers.org/aop/136
#+     - http://identifiers.org/aop/138
#+     - http://identifiers.org/aop/139
#+     - http://identifiers.org/aop/141
#+     - http://identifiers.org/aop/144
#+     - http://identifiers.org/aop/146
#+     - http://identifiers.org/aop/148
#+     - http://identifiers.org/aop/149
#+     - http://identifiers.org/aop/150
#+     - http://identifiers.org/aop/151
#+     - http://identifiers.org/aop/152
#+     - http://identifiers.org/aop/153
#+     - http://identifiers.org/aop/154
#+     - http://identifiers.org/aop/155
#+     - http://identifiers.org/aop/156
#+     - http://identifiers.org/aop/157
#+     - http://identifiers.org/aop/158
#+     - http://identifiers.org/aop/159
#+     - http://identifiers.org/aop/160
#+     - http://identifiers.org/aop/161
#+     - http://identifiers.org/aop/162
#+     - http://identifiers.org/aop/163
#+     - http://identifiers.org/aop/164
#+     - http://identifiers.org/aop/165
#+     - http://identifiers.org/aop/166
#+     - http://identifiers.org/aop/167
#+     - http://identifiers.org/aop/168
#+     - http://identifiers.org/aop/169
#+     - http://identifiers.org/aop/170
#+     - http://identifiers.org/aop/171
#+     - http://identifiers.org/aop/173
#+     - http://identifiers.org/aop/175
#+     - http://identifiers.org/aop/176
#+     - http://identifiers.org/aop/177
#+     - http://identifiers.org/aop/178
#+     - http://identifiers.org/aop/179
#+     - http://identifiers.org/aop/180
#+     - http://identifiers.org/aop/181
#+     - http://identifiers.org/aop/182
#+     - http://identifiers.org/aop/183
#+     - http://identifiers.org/aop/184
#+     - http://identifiers.org/aop/185
#+     - http://identifiers.org/aop/186
#+     - http://identifiers.org/aop/187
#+     - http://identifiers.org/aop/188
#+     - http://identifiers.org/aop/189
#+     - http://identifiers.org/aop/190
#+     - http://identifiers.org/aop/191
#+     - http://identifiers.org/aop/192
#+     - http://identifiers.org/aop/193
#+     - http://identifiers.org/aop/194
#+     - http://identifiers.org/aop/195
#+     - http://identifiers.org/aop/196
#+     - http://identifiers.org/aop/197
#+     - http://identifiers.org/aop/199
#+     - http://identifiers.org/aop/200
#+     - http://identifiers.org/aop/201
#+     - http://identifiers.org/aop/202
#+     - http://identifiers.org/aop/203
#+     - http://identifiers.org/aop/204
#+     - http://identifiers.org/aop/205
#+     - http://identifiers.org/aop/206
#+     - http://identifiers.org/aop/207
#+     - http://identifiers.org/aop/208
#+     - http://identifiers.org/aop/209
#+     - http://identifiers.org/aop/210
#+     - http://identifiers.org/aop/211
#+     - http://identifiers.org/aop/212
#+     - http://identifiers.org/aop/213
#+     - http://identifiers.org/aop/214
#+     - http://identifiers.org/aop/215
#+     - http://identifiers.org/aop/216
#+     - http://identifiers.org/aop/217
#+     - http://identifiers.org/aop/218
#+     - http://identifiers.org/aop/219
#+     - http://identifiers.org/aop/220
#+     - http://identifiers.org/aop/221
#+     - http://identifiers.org/aop/222
#+     - http://identifiers.org/aop/223
#+     - http://identifiers.org/aop/224
#+     - http://identifiers.org/aop/225
#+     - http://identifiers.org/aop/226
#+     - http://identifiers.org/aop/227
#+     - http://identifiers.org/aop/228
#+     - http://identifiers.org/aop/229
#+     - http://identifiers.org/aop/230
#+     - http://identifiers.org/aop/231
#+     - http://identifiers.org/aop/232
#+     - http://identifiers.org/aop/233
#+     - http://identifiers.org/aop/234
#+     - http://identifiers.org/aop/235
#+     - http://identifiers.org/aop/236
#+     - http://identifiers.org/aop/237
#+     - http://identifiers.org/aop/238
#+     - http://identifiers.org/aop/239
#+     - http://identifiers.org/aop/240
#+     - http://identifiers.org/aop/241
#+     - http://identifiers.org/aop/242
#+     - http://identifiers.org/aop/245
#+     - http://identifiers.org/aop/256
#+     - http://identifiers.org/aop/257
#+     - http://identifiers.org/aop/258
#+     - http://identifiers.org/aop/259
#+     - http://identifiers.org/aop/260
#+     - http://identifiers.org/aop/261
#+     - http://identifiers.org/aop/262
#+     - http://identifiers.org/aop/263
#+     - http://identifiers.org/aop/264
#+     - http://identifiers.org/aop/265
#+     - http://identifiers.org/aop/266
#+     - http://identifiers.org/aop/267
#+     - http://identifiers.org/aop/268

prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix aop: <http://identifiers.org/aop/>
prefix aopo: <http://aopkb.org/aop_ontology#>
prefix mmo: <http://purl.obolibrary.org/obo/MMO_>

select ?AopLabel?KeLookUp ?AssayText
where {
 ?KeLook a aopo:KeyEvent ;
 rdfs:label ?KeLookUp ;
 dcterms:isPartOf ?_aopfilter_iri ; 
 mmo:0000000 ?AssayText .
 ?_aopfilter_iri rdfs:label ?AopLabel .
}
