#+ summary: Get AOP for a specific chemical (CAS ID). For the variable of casfilter, fill the CAS-RN of interest. 
#+ endpoint_in_url: False
#+ tags:
#+   - Adverse Outcome Pathways
#+ defaults:
#+   - casfilter: 107-18-6

PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX cheminf: <http://semanticscience.org/resource/CHEMINF_>

SELECT ?CAS ?ChemicalName ?AOPwebpage ?AdverseOutcomePathwayName ?MIEwebpage ?MolecularInitiatingEventName
WHERE {
 ?Chemical a cheminf:000000 ;
 dc:title ?ChemicalName ;
 cheminf:000446 ?CAS ;
 dcterms:isPartOf ?Stressor .
 ?Stressor a nci:C54571 ;
 dcterms:isPartOf ?AOPwebpage .
 ?AOPwebpage a aopo:AdverseOutcomePathway ;
 aopo:has_molecular_initiating_event ?MIEwebpage ;
 dc:title ?AdverseOutcomePathwayName.
 ?MIEwebpage dc:title ?MolecularInitiatingEventName .
FILTER regex (?CAS, ?_CASfilter_en, "i")
}
