#+ summary: Get all chemical that are present in the AOP-Wiki.
#+ endpoint_in_url: False
#+ tags:
#+   - Dump

PREFIX cas: <http://identifiers.org/cas/>
PREFIX cheminf: <http://semanticscience.org/resource/CHEMINF_>

SELECT ?CAS ?ChemicalName
WHERE {
 ?cas a cheminf:000000 ;
 dc:title ?ChemicalName ;
 cheminf:000446 ?CAS . 
}
