#+ summary: Get all chemical that are part of a particular AOP.
#+ endpoint_in_url: False
#+ tags:
#+   - Adverse Outcome Pathways
#+   - Chemicals
#+ defaults:
#+   - aopfilter: 37

PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX cheminf: <http://semanticscience.org/resource/CHEMINF_>
PREFIX nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

SELECT ?CASID ?ChemicalName
WHERE{
?aop a aopo:AdverseOutcomePathway; nci:C54571 ?Stressor.
?Stressor aopo:has_chemical_entity ?Chemical.
?Chemical cheminf:000446 ?CASID; dc:title ?ChemicalName.
BIND(IRI(CONCAT("https://identifiers.org/aop/",?_aopfilter_integer)) AS ?AOPf )
FILTER (?aop = ?AOPf)
}
