#+ summary: Get Adverse Outcome Pathways from Adverse Outcome name (literal).
#+ endpoint_in_url: False
#+ tags:
#+   - Adverse Outcome Pathways
#+ defaults:
#+   - AOfilter: 341

prefix aop: <http://identifiers.org/aop/> 
prefix aopo: <http://aopkb.org/aop_ontology#> 
prefix ke: <http://identifiers.org/aop.events/>

SELECT ?KE ?KEname ?AOP ?AOPname WHERE { 
  ?KE a aopo:KeyEvent ; 
  dc:identifier ?AOLookup ; 
  dc:title ?KEname . 
  ?AOP a aopo:AdverseOutcomePathway ; 
  dc:title ?AOPname ; 
  aopo:has_adverse_outcome ?AOLookup.
 FILTER regex (?AOname, ?_AOfilter_en, "i")}
