#+ summary: Get chemicals from any Key Event (ID).
#+ endpoint_in_url: False
#+ tags:
#+   - Chemicals
#+ defaults:
#+   - KEfilter: 341

prefix aopo: <http://aopkb.org/aop_ontology#> 
prefix nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
prefix cheminf: <http://semanticscience.org/resource/CHEMINF_>

SELECT ?KEname ?AOP ?MIE ?MIEname ?stressor ?chemical ?Chemname  WHERE { 
  ?KE a aopo:KeyEvent ; dc:identifier ?KELookup ; dc:title ?KEname . 
  ?AOP a aopo:AdverseOutcomePathway ; dc:title ?AOPname ; aopo:has_key_event ?KELookup; aopo:has_molecular_initiating_event ?MIE. 
  ?MIE dc:title ?MIEname .
  ?stressor a nci:C54571 ; dcterms:isPartOf ?MIE .
  ?chemical a cheminf:000000 ; dcterms:isPartOf ?stressor ; dc:title ?Chemname. 
BIND(IRI(CONCAT("https://identifiers.org/aop.events/",?_KEfilter_integer)) AS ?KEf )
FILTER (?KE = ?KEf)}
ORDER BY ASC(?AOP)
