#+ summary: Get all chemical that are part of a particular AOP.
#+ endpoint_in_url: False
#+ tags:
#+   - Adverse Outcome Pathways
#+   - Chemicals
#+ defaults:
#+   - aofilter: 341

PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX cheminf: <http://semanticscience.org/resource/CHEMINF_>
PREFIX nci: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

SELECT DISTINCT ?AOname ?CASID   WHERE { 
  ?AO a aopo:KeyEvent ; dc:title ?AOname . 
  ?AOP a aopo:AdverseOutcomePathway ;  aopo:has_adverse_outcome ?AO ; nci:C54571 ?Stressor.
?Stressor aopo:has_chemical_entity ?Chemical.
?Chemical cheminf:000446 ?CASID.
BIND(IRI(CONCAT("https://identifiers.org/aop.events/",?_aopfilter_integer)) AS ?AOf )
FILTER (?AO = ?AOf)
}
