#+ summary: Get all AOPs that are present in the AOP-Wiki.
#+ endpoint_in_url: False
#+ tags:
#+   - Dump

PREFIX aopo: <http://aopkb.org/aop_ontology#>

SELECT ?AO ?AOTitle ?AOID
WHERE {
 ?AOP a aopo:AdverseOutcomePathway ; aopo:has_adverse_outcome ?AO .
 ?AO dc:title ?AOTitle ;
 rdfs:label ?AOID . 
}
