#+ summary: Get all AOPs that are present in the AOP-Wiki.
#+ endpoint_in_url: False
#+ tags:
#+   - Dump

PREFIX aopo: <http://aopkb.org/aop_ontology#>

SELECT ?AOP ?AOPTitle ?AOPID
WHERE {
 ?AOP a aopo:AdverseOutcomePathway ;
 dc:title ?AOPTitle ;
 rdfs:label ?AOPID . 
}
