#+ summary: Get alternative identifiers for a specific chemical. For the variable of casfilter, fill the complete URI for the CAS-RN. This consists of "http://identifiers.org/cas/" + the CAS-RN of interest. In this example, this is "107-18-6"/ Therefore, the variable casfilter has "http://identifiers.org/cas/107-18-6" as a default value.
#+ endpoint_in_url: False
#+ tags:
#+   - Chemicals
#+ defaults:
#+   - casfilter: http://identifiers.org/cas/107-18-6

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX casrn: <http://identifiers.org/cas/>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?CAS ?ChemicalName 
WHERE {
 ?_casfilter_uri a cheminf:CHEMINF_000000 ;
 dc:title ?ChemicalName ;
 cheminf:CHEMINF_000446 ?CAS  . 
}
